### ISSUE TITLE
Add docker context

### ISSUE THREAD

**Issue by collabnix** [collabnix/dockertools#24]
[Docker Context](https://docs.docker.com/engine/context/working-with-contexts/) - Makes it easy to switch between multiple Docker and Kubernetes environments.

**Comment by collabnix** [comment]
@0904-mansi

**Comment by 0904-mansi** [comment]
> [Docker Context](https://docs.docker.com/engine/context/working-with-contexts/) - Makes it easy to switch between multiple Docker and Kubernetes environments.

Its already in the list
